Tidy up a bit

diff --git a/docker_reg_tool b/docker_reg_tool
--- a/docker_reg_tool
+++ b/docker_reg_tool
@@ -1,4 +1,5 @@
 #!/bin/bash
+#
 set -euo pipefail
 
 CMD=$0
@@ -6,30 +7,25 @@ CMD=$0
 function usage {
     cat <<EOU
 
-    Usage: 
+    Usage:
 
     $CMD REGISTRY_BASE_URL ACTION [OPTIONS..]
-    
+
     Actions:
-
     - list               list repos
-
     - list REPO          list tags for repo
-
     - delete REPO TAG    delete tag for repo
 
-    Example:
+    Examples:
 
     List all repos
-        /$ $CMD https://registry.my.domain list
+        $CMD https://registry.my.domain list
 
     List tags for one repo
-        /$ $CMD https://registry.my.domain list some-repo
+        $CMD https://registry.my.domain list some-repo
 
     Delete tag for a repo
-        /$ $CMD https://registry.my.domain delete some-repo
-
-
+        $CMD https://registry.my.domain delete some-repo
 EOU
     exit 1
 }
@@ -37,52 +33,63 @@ EOU
 [ $# -lt 2 ] && usage
 
 set +e
-PROTO="$(echo $1 | grep :// | sed -e's,^\(.*://\).*,\1,g')"
+PROTO="$(echo "$1" | grep :// | sed -e's,^\(.*://\).*,\1,g')"
 set -e
 
 [ -z "$PROTO" ] && >&2 echo "ERROR: Must have protocol in registry url" && usage
 
 # remove the protocol
-REG="$(echo ${1/$PROTO/})"
+REG=${1/$PROTO/}
 shift
 ACTION="$1"
 shift
 
 CREDS=""
-if [[ -f "~/.docker/config.json" ]]; then
-    CREDS="Authorization: Basic $(jq -r '.auths."'$REG'".auth' < ~/.docker/config.json)"
+if [[ -f "${HOME}/.docker/config.json" ]]; then
+  CREDS="Authorization: Basic $(jq -r ".auths.\"$REG\".auth" < "${HOME}/.docker/config.json")"
 elif [[ -v "BASIC_AUTH" ]]; then
-    CREDS="Authorization: Basic $(echo -n $BASIC_AUTH|base64)"
+  CREDS="Authorization: Basic $(echo -n "$BASIC_AUTH"|base64)"
 fi
 
 
 case "$ACTION" in
-    list)
-        if [ $# -eq 1 ]; then
-            repo=${1}
-            if [ -n "$repo" ]; then
-                curl -s --header "$CREDS" $PROTO$REG/v2/$repo/tags/list | jq -r '.tags|.[]'
-            fi
-        else
-            curl -s --header "$CREDS" $PROTO$REG/v2/_catalog | jq -r '.repositories|.[]'
-        fi
+  list)
+    if [ $# -eq 1 ]; then
+      repo=${1}
+      if [ -n "$repo" ]; then
+        curl -s --header "$CREDS" "$PROTO$REG/v2/$repo/tags/list" | jq -r '.tags|.[]'
+      fi
+    else
+      curl -s --header "$CREDS" "$PROTO$REG/v2/_catalog" | jq -r '.repositories|.[]'
+    fi
 
-        ;;
-    delete)
-        repo=$1
-        tag=$2
-        digest=$(curl -v -s --header "$CREDS" -H "Accept:application/vnd.docker.distribution.manifest.v2+json" $PROTO$REG/v2/$repo/manifests/$tag 2>&1 |grep "< Docker-Content-Digest:"|awk '{print $3}')
-        digest=${digest//[$'\t\r\n']}
-        echo "DIGEST: $digest"
-        result=$(curl --header "$CREDS"  -s -o /dev/null -w "%{http_code}" -H "Accept:application/vnd.docker.distribution.manifest.v2+json" -X DELETE "$PROTO$REG/v2/$repo/manifests/$digest")
-        if [ $result -eq 202 ]; then
-            echo "Successfully deleted"
-            exit 0
-        else 
-            echo "Failed to delete"
-            exit 3
-        fi
-        ;;
+    ;;
+  delete)
+    repo=$1
+    tag=$2
+    digest=$(curl -sS -D - \
+      --header "$CREDS" \
+      --header "Accept:application/vnd.docker.distribution.manifest.v2+json" \
+      "$PROTO$REG/v2/$repo/manifests/$tag" |
+    grep ^Docker-Content-Digest | awk '{print $2}')
+    digest=${digest//[$'\t\r\n']}
+    echo "DIGEST: $digest"
+
+    result=$(curl --header "$CREDS" \
+      --header "Accept:application/vnd.docker.distribution.manifest.v2+json" \
+      -s -o /dev/null -w "%{http_code}" \
+      -X DELETE "$PROTO$REG/v2/$repo/manifests/$digest")
+    if [ "$result" -eq 202 ]; then
+      echo "Successfully deleted"
+      exit 0
+    elif [ "$result" -eq 405 ]; then
+      echo "Failed to delete, HTTP ${result}.  Maybe the registry is not new" \
+        "enough to support DELETE?"
+    else
+      echo "Failed to delete: HTTP ${result}"
+      exit 3
+    fi
+    ;;
 esac
 
 
